// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouZQ7SBtV6fXX00IACy0Gak5iNwhC6YI',
    appId: '1:475680856811:web:b9f7a142498ac966b0bcae',
    messagingSenderId: '475680856811',
    projectId: 'reloved-4cdc6',
    authDomain: 'reloved-4cdc6.firebaseapp.com',
    storageBucket: 'reloved-4cdc6.appspot.com',
    measurementId: 'G-DSNLLZ6NYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzxADkzz5iokAaoc7rYCswhv8pYb4B_k',
    appId: '1:475680856811:android:5d29eccd9662d838b0bcae',
    messagingSenderId: '475680856811',
    projectId: 'reloved-4cdc6',
    storageBucket: 'reloved-4cdc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkaTyYIAUlikTGdVaHi4S8s6u827iu7Og',
    appId: '1:475680856811:ios:7a20286c3061fa9ab0bcae',
    messagingSenderId: '475680856811',
    projectId: 'reloved-4cdc6',
    storageBucket: 'reloved-4cdc6.appspot.com',
    iosBundleId: 'com.example.reloved',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkaTyYIAUlikTGdVaHi4S8s6u827iu7Og',
    appId: '1:475680856811:ios:7a20286c3061fa9ab0bcae',
    messagingSenderId: '475680856811',
    projectId: 'reloved-4cdc6',
    storageBucket: 'reloved-4cdc6.appspot.com',
    iosBundleId: 'com.example.reloved',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCouZQ7SBtV6fXX00IACy0Gak5iNwhC6YI',
    appId: '1:475680856811:web:ff036dacb88cbccbb0bcae',
    messagingSenderId: '475680856811',
    projectId: 'reloved-4cdc6',
    authDomain: 'reloved-4cdc6.firebaseapp.com',
    storageBucket: 'reloved-4cdc6.appspot.com',
    measurementId: 'G-S570E8PCR5',
  );
}
